name: Deploy to Github Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          yarn
          yarn global add parcel
          yarn prebuild
          parcel build --no-source-maps
          yarn postbuild
          sed -i 's/{gh_actions_replace_hash}/${{ github.sha }}/' dist/index.html

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v5

      - name: Upload artifact 📁
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
